---
version: "3"

vars:
    USER: yc-user
    SSH_KEY_PATH: ~/.ssh/dev-hosts

tasks:
    sync-source:
        desc: Sync files with the source server.
        cmds:
            - rsync -az -e "ssh -i {{ .SSH_KEY_PATH }}" --progress $(pwd) {{ .USER }}@$VM_SOURCE_EXT_IP:/home/{{ .USER }}/code/

    sync-target:
        desc: Sync files with the target server.
        cmds:
            - rsync -az -e "ssh -i {{ .SSH_KEY_PATH }}" --progress $(pwd) {{ .USER }}@$VM_TARGET_EXT_IP:/home/{{ .USER }}/code/
